=== nutsjian/json-schema-validator/src/test/resources/dev/schema/order_array.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Order Array",
  "description": "A order array",
  "type": "array",
  "items": {
    "title": "Order",
    "type": "object",
    "properties": {
      "order_no": {
        "type": "string",
        "description": "",
        "requiredErrorCode": "订单号必须"
      },
      "amount": {
        "description": "Name of the product",
        "type": "number",
        "minimum": 1000,
        "exclusiveMinimum": true,
        "typeErrorCode": "ajsdjkasdjkas",
        "minimumErrorCode": "xxxxxxx"
      },
      "consignee": {
        "type": "string",
        "minLength": 1
      },
      "phone": {
        "type": "string",
        "minLength": 11,
        "maxLength": 11,
        "minLengthErrorCode": "minLength error",
        "maxLengthErrorCode": "maxLength error",
        "patternErrorCode": "pattern error"
      },
      "region": {
        "type": "string",
        "minLength": 1
      },
      "address": {
        "type": "string"
      }
    },
    "required": ["order_no", "amount", "consignee", "phone", "region"]
  }
}

=== nutsjian/json-schema-validator/src/test/resources/dev/data/order_array_test.json
[
  {
    "order_no": "2017111401",
    "amount": 988.00,
    "consignee": "王先生",
    "phone": "13913580888",
    "region": "江苏省苏州市吴中区",
    "address": "XX路999号"
  },
  {
    "order_no": "2017111402",
    "amount": 388.00,
    "consignee": "田先生",
    "phone": "13913580000",
    "region": "江苏省苏州市吴中区",
    "address": "林泉街333号"
  }
]
